name: Fork CI

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

permissions:
  contents: read

jobs:
  format:
    runs-on: ubuntu-24.04
    name: Format (Fork)
    steps:
      - uses: actions/checkout@v7
      - run: cargo fmt -- --check

  lint:
    runs-on: ubuntu-24.04
    name: Clippy (Fork)
    steps:
      - uses: actions/checkout@v7
      - run: cargo clippy --all-features -- --deny warnings

  test:
    runs-on: ubuntu-24.04
    name: Test (Fork)
    steps:
      - uses: actions/checkout@v7
      - run: cargo test --all-features
